apiVersion: skaffold/v2beta8
kind: Config
metadata:
  name: module-estimator
build:
  artifacts:
  - image: calculator
deploy:
  kubectl:
    manifests:
    - manifests/calculator-pod.yaml
    - manifests/calculator-service.yaml
    - manifests/webnet-networkpolicy.yaml
    - manifests/ingress.yaml
